spring:
  application:
    name: petresearch
  threads:
    virtual:
      enabled: true
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/petresearch
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 2000ms
  
  # Cache Configuration
  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false
  
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      read-date-timestamps-as-nanoseconds: false
  
  # Quartz Configuration
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: QRTZ_
            useProperties: true

# Server Configuration
server:
  port: 8080

# Logging
logging:
  level:
    org.roman.petresearch: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cache: DEBUG

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,quartz
  endpoint:
    health:
      show-details: when-authorized
    quartz:
      enabled: true
      show-details: always
